### ISSUE TITLE
Koble på kontakt-meg-backend

### ISSUE THREAD

**Issue by eriksalhus** [sceltoas/scelto-web#11]
Jeg har opprettet en email-backend som jeg tenkte å deploye på en gratis heroku-instans, eller kanskje azure er bedre?

@herms Har du ferdigstilt backend-tjenesten? Hvis ikke, har vi et sted jeg kan deploye node-modulen min og se om det ruller? Problemet med heroku er at den ikke er oppe 100% og sover etter 30 min inaktivitet. Vi trenger kanskje ikke mer, men greit å bruke azure hvis det er gratis...

**Comment by ivarni** [comment]
Du får 100% oppetid på Heroku for $7 pr mnd om du velger hobby-instans. Da får du også mulighet for å sette opp SSL. Når DET er sagt fungerer Firebase også veldig bra og der endte det opp med å koste gratis så jeg switchet over i sommer en gang.

**Comment by herms** [comment]
https://api.scel.to/Contact/SendEmail
Content-Type: application/json
Body: 
{"Name":"Herman (test)","PhoneNumber":"97727277"}

**Comment by eriksalhus** [comment]
Denne er nå utført @herms , men jeg får det ikke til å fungere. Gjerne se på det og gi meg tilbakemelding på hva jeg skal gjøre.

**Comment by herms** [comment]
Done and done.
