### ISSUE TITLE
Glitcher når man skriver navn inn på kontakt oss siden

### ISSUE THREAD

**Issue by TerjeLon** [sceltoas/scelto-web#23]
Når man skriver inn navn, så hopper tekstfeltet opp på linjen over, se bilder:

![Screenshot 2020-03-05 at 12 59 03](https://user-images.githubusercontent.com/6603458/75979592-1b7c3980-5ee1-11ea-8520-659341deedcd.png)
![Screenshot 2020-03-05 at 12 58 28](https://user-images.githubusercontent.com/6603458/75979637-39499e80-5ee1-11ea-820a-e5b35314ea54.png)

**Comment by seanes** [comment]
Ikke helt relatert, men muligens overlappende bug i designtankesett: #19 
Imho er `contentEditable` bedre når innholdet er `in-line`.
