### ISSUE TITLE
Deploy til prod ved push til master

### ISSUE THREAD

**Issue by eriksalhus** [sceltoas/scelto-web#26]
Hva tenker du @herms? Hvordan skal vi løse dette?

**Comment by TerjeLon** [comment]
Hvordan deployes det nå? Kan jo bruke github actions for å automatisk deploye?

**Comment by herms** [comment]
@eriksalhus @TerjeLon Det er bare en liten innstilling i Azure, jeg kan fikse i morgen. Burde samtidig ha en staging branch (eller bare bruke develop) som kan deployes til staging ved push..? Eller ska're alltid rett i prod, tenker dere?

**Comment by eriksalhus** [comment]
Jeg tenker at master kan gå rett i prod. Vi kan da også skru på påtvungen PR på alt som skal inn i master. Hva tenker dere om det @herms og @TerjeLon ?

**Comment by eriksalhus** [comment]
> Det er bare en liten innstilling i Azure, jeg kan fikse i morgen

Hellz yeah!

**Comment by eriksalhus** [comment]
> Hvordan deployes det nå? Kan jo bruke github actions for å automatisk deploye?

Manuelt via FTP (filezilla o.l.) 🤷

**Comment by herms** [comment]
> 
> 
> Jeg tenker at master kan gå rett i prod. Vi kan da også skru på påtvungen PR på alt som skal inn i master. Hva tenker dere om det @herms og @TerjeLon ?

Tvungen PR er nok lurt! Sjelden det brenner såpass at man ikke kan vente litt 😄

**Comment by herms** [comment]
Pipeline oppdatert.

**Comment by TerjeLon** [comment]
> > 
> 
> > 
> 
> > Jeg tenker at master kan gå rett i prod. Vi kan da også skru på påtvungen PR på alt som skal inn i master. Hva tenker dere om det @herms og @TerjeLon ?
> 
> 
> 
> Tvungen PR er nok lurt! Sjelden det brenner såpass at man ikke kan vente litt 😄 

Gjør vi Sceltianere feil altså? TIL

**Comment by herms** [comment]
Ingen feil selvsagt, men det er jo hyggelig når andre får lese den deilige, feilfrie koden!

**Comment by ivarni** [comment]
https://www.youtube.com/watch?v=wCsO56kWwTc
