### ISSUE TITLE
Fikse feil på de tre ansatte på forsiden

### ISSUE THREAD

**Issue by eriksalhus** [sceltoas/scelto-web#9]
Usikker på hvorfor, men bildene blir ikke lastet riktig og navn passer ikke med lenken som den fører til... her kan det være feil i flere områder...

Det fungerer lokalt og lokalt i prodbygg så her må det graves...

**Comment by ismarslomic** [comment]
Ser også at URL i lenken (på bildet og navn) blir helt random/feil

**Comment by ismarslomic** [comment]
Har dog ikke klart å reprodusere feilen når jeg kjører lokalt på maskinen (med `npm start `eller `npm run start:prod`).

**Comment by ismarslomic** [comment]
Dette er meget rart. Som du sier kan man ikke reprodusere feilen på lokal server (dev eller prod bygg). Når jeg debugger https://eager-shaw-fd1f4c.netlify.com/ansatte/ settes riktig props i React-komponentene, men HTML blir feil. Legger ved noen screenshots.

<img width="1005" alt="js" src="https://user-images.githubusercontent.com/2174314/70866106-afcfa380-1f65-11ea-8df4-53199474b5e6.png">
<img width="757" alt="html-elements" src="https://user-images.githubusercontent.com/2174314/70866107-afcfa380-1f65-11ea-8cbe-b4765cdc4bb3.png">
<img width="1052" alt="react-props" src="https://user-images.githubusercontent.com/2174314/70866108-b0683a00-1f65-11ea-9784-a55e2f6578f3.png">

**Comment by eriksalhus** [comment]
Jeg får dette ikke helt til å stemme. Kan virke som at Netlify får et annet resultat på bygging enn jeg får. Hvis jeg bygger og fyrer det opp med `reload` e.l. så fungerer prod-bygget helt fint.
